### ISSUE TITLE
Compound

### ISSUE THREAD

**Issue by ghost** [robinandeer/scout#123]
That the variant under investigation is also included in the pop-up for AR_compounds and in table on the variant info page. Otherwise it is harder to investigate the carrier status of the parents.

submitted by **Henrik Stranneheim**.

**Comment by mitochris** [comment]
I would also like to add that the order of subjects in the actual variant is different to the oder in the additional compound hits. i.e. in the variant it is: x-1-1A, x-2-1U, x-2-2U, while for the compounds it is: x-2-1U, x-2-2U, x-1-1A. It is more difficult to follow the inheritance.
