### ISSUE TITLE
HGMD link to mutation 

### ISSUE THREAD

**Issue by ghost** [robinandeer/scout#128]
https://clinical-db.scilifelab.se:8081/#/family/137/variants/49103822?database=IEM&offset=0

this variant is reported in the HGMD but this info is not coming out.

submitted by **Michela Barbaro**.

**Comment by robinandeer** [comment]
@henrikstranneheim What do you think about this? Can you check in the source files, I can't see any HGMD annotation in the call from the database.

**Comment by henrikstranneheim** [comment]
I only have a C>T change at that position and no G>A as in the variant call in Scout. I guess this could be that the hgmdgff is strand specific in its variant call. That is not something that I have included in the parsing.

Will have to remedy that in the next upgrade. 

/H

On 24 Mar 2014, at 13:53, Robin Andeer notifications@github.com wrote:

> @henrikstranneheim What do you think about this? Can you check in the source files, I can't see any HGMD annotation in the call from the database.
> 
> —
> Reply to this email directly or view it on GitHub.

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory, KISP
SE-171 65 Solna, Sweden

E-mail: henrik.stranneheim@scilifelab.se
Visiting address: Tometebodavägen 23A
