### ISSUE TITLE
Caching av information?

### ISSUE THREAD

**Issue by MatsDahlberg** [robinandeer/scout#135]
Nu när det finns 4 olika instanser så behöver jag logga in de olika instanserna för att kolla så att allt ser ut som det ska.

Jag har testat att logga ut ur chrome och sedan ändra i databasen så att min mail tillhör en annan instans. Sedan loggar jag på igen. Men flask-servern fortsätter att använda samma instans som jag hade i den gamla sessionen.

Har även testat att öppna firefox istället (har aldrig tidigare använt ff med scout) och även med ff så används den gamla instansen (så det verkar spilla över information i flask-servern om vilken instans som min IP-adress varit kopplad mot).

Tror det är viktigt att flask-servern tömmer all information när man trycker på logga-ut knappen.

**Comment by robinandeer** [comment]
Det är jag som tänkt fel - för att spara kommentarer tänkte jag att det kunde vara en bra idé att koppla användare-dokument/records.

Men då måste jag ju antingen inte spara information som kan uppdateras eller kolla din databas varje gång någon loggar in och uppdatera ny information.
