### ISSUE TITLE
Select instance tag

### ISSUE THREAD

**Issue by robinandeer** [robinandeer/scout#136]
- [x] Before showing families list => user selects from list of instance tags
- [x] Show selected instance tag in sidebar?

**Comment by MatsDahlberg** [comment]
Eftersom du redan skickar med 'institute' (institute är samma sak som instance) som en cookie i alla anrop till backend så skulle du kunna sätta den till den instans som användaren har valt.

På så sätt behöver vi inte ändra på något i interfacet mellan frontend och backend.

**Comment by robinandeer** [comment]
Då måste vi bara komma på ngt sätt att förhindra användare från att sätta "institute" till något som de inte borde göra.

Annars tänkte jag att jag lägger till "institute" eller "database" some en query-param i callet till "families".

**Comment by MatsDahlberg** [comment]
Jag trodde att det var du som satte 'institute' så det enda som borde behövas är att du sätter 'institute' till ett av värdena i:

```
{
    "institute": "CMMS,BioNut", 
    "user_name": "Mats Dahlberg", 
    "email": "mats.dahlberg@scilifelab.se"
}
```

Så om anvädaren sätter 'institute' till något ogiltigt så borde det kollas mot listan ovan. Eller hur funkar det?

Annars gör vi som du säger och lägger till en parameter 'instance', men den måste isåfall läggas på i alla anrop:

```
http://clinical-db:8082/families
http://clinical-db:8082/families/99/variants?database=iem
http://clinical-db:8082/families/1/filter
```

**Comment by MatsDahlberg** [comment]
Vid närmare eftertanke så måste nog 'instance' finnas med i URL:en. Annars är det inte säkert att en användare kan maila en länk till en annan användare.

Men någonstans så måste det göras en check att den användare som är inloggad har rätt att kolla på den instancen som efterfrågas. Kollar du att den inloggade anvädaren har rätt att kolla på den instance som du skickar till mig?

**Comment by robinandeer** [comment]
Nej, jag matchar inte instance mot listan men det kan jag fixa.

**Comment by MatsDahlberg** [comment]
Nu har jag implementerat följande på http://clinical-db:8084/:

```
http://clinical-db:8084/families/133/variants?institute=CMMS
http://clinical-db:8084/families/133/filter?institute=CMMS
http://clinical-db:8084/families/133?institute=CMMS
http://clinical-db:8084/families/133/variants?database=IEM&relation=LESSER&offset=0&institute=CMMS
```

Om dessa routes anropas utan `institute=CMMS` så returneras en tom sträng.
