### ISSUE TITLE
Filtrear på rätt databas

### ISSUE THREAD

**Issue by MatsDahlberg** [robinandeer/scout#137]
Familjen 1 i instansen TIU är körd mot 'research' och en databas som heter 'PID'.

Men när man loggar in som en användare av instansen TIU och sedan trycker på länken till varianter för familj '1' så anropas backend med denna länk:
http://clinical-db:8082/families/1/variants?database=IEM&relation=LESSER

Dvs 'database=IEM', detta gör att databasen inte returnerar några varianter för familjen. 
Den JSON som returneras av http://clinical-db:8082/families har en tag för varje familj som innehåller databasen:

```
        "database": "PID,research"
```

Någon av dessa databaserna borde vara med i anropet så att backend kan göra ett filter som returnerar varianter.

**Comment by robinandeer** [comment]
Nu sätts default-databasen dynamiskt. Ska pusha koden clinical-db snart.

Kan man lita på ordningen? Kommer research alltid ligga som sista alternativ?

**Comment by MatsDahlberg** [comment]
Just nu sorterar jag inte listan. Jag kan sortera listan i bokstavsordning om du vill?

**Comment by MatsDahlberg** [comment]
Nu har jag fixat så att 'research' kommer sist.

**Comment by robinandeer** [comment]
Jag borde förmodligen hitta på något smartare framöver men det är skönt om det funkar så här så länge :)
