### ISSUE TITLE
 Disease_gene_model

### ISSUE THREAD

**Issue by henrikstranneheim** [robinandeer/scout#23]
## COLUMNNAME="Disease_gene_model"       TYPE="String"   DESCRIPTION="Known disease inheritance model"   SCOUTHEADER="Disease Gene Model"

e.g. "AR"
1. Include the  Disease_gene_model  values in the clinical list.
2. Preset the Inheritance model after the the disease gene model entries in the clinical list, when clicking "clinical filter".

**Comment by robinandeer** [comment]
Do we have this information in the database now?

**Comment by henrikstranneheim** [comment]
No, we have not implemented it in dbCV.

On 21 Jan 2014, at 09:51, Robin Andeer notifications@github.com wrote:

> Do we have this information in the database now?
> 
> —
> Reply to this email directly or view it on GitHub.

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory, KISP
SE-171 65 Solna, Sweden

E-mail: henrik.stranneheim@scilifelab.se
Phone: +46 (0)8 524 81487 (Office) 
Phone: +46 (0)736251487 (Mobile)
Visiting address: Tometebodavägen 23A
