### ISSUE TITLE
IEM/EP

### ISSUE THREAD

**Issue by henrikstranneheim** [robinandeer/scout#25]
## COLUMNNAME="Clinical_db_gene_annotation"      TYPE="String"   DESCRIPTION="Genes associated with a disease group e.g., IEM, EP"       SCOUTHEADER="Clinical db Gene Annotation"

e.g. IEM:EP
1. Add flag to choose IEM and/or EP in clinical list filtering. 
2. Clincal list filter default: both enabled.

**Comment by robinandeer** [comment]
Why not one list with all variants? IEM/EP/Research field.

**Comment by henrikstranneheim** [comment]
Yes, why not! That’s a good point!

As long as there is no risk of seeing a research variant by default there should be no problem. In addition there should be no research variants unless full consent is achieved and then it does not matter. 

Let’s have one list of variants and the tick box decides, what to show. Be aware though that the clinical and research lists are two separate infiles, with differently sorted rank scores. Maybe one should be able to choose clinical Disease association like IEM;EP:..N, OR research candidates but not clinical and research at the same time. The you can avoid the issues with the input and we can still have clear separation of candidates. 

By default research list should be off as a security matter. 

/H
On 27 Jan 2014, at 13:54, Robin Andeer notifications@github.com wrote:

> Why not one list with all variants? IEM/EP/Research field.
> 
> —
> Reply to this email directly or view it on GitHub.

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory, KISP
SE-171 65 Solna, Sweden

E-mail: henrik.stranneheim@scilifelab.se
Phone: +46 (0)8 524 81487 (Office) 
Phone: +46 (0)736251487 (Mobile)
Visiting address: Tometebodavägen 23A

**Comment by robinandeer** [comment]
Nu kan man byta mellan databaser men inte research
