### ISSUE TITLE
Enable create/update/export of pedigree files in Scout.

### ISSUE THREAD

**Issue by henrikstranneheim** [robinandeer/scout#26]
The pedigree file should follow the format described here:
http://mip-api.readthedocs.org/en/latest/pedigree_file.html
- [ ] Enable new/updated information to be added to already existing entries.
- [ ] Enable novel entries to be created as long as they adhere to the format mentioned above.
- [ ] Export pedigree file from scout to use in MIP analysis.
- [x] Show pedigree in Scout

**Comment by robinandeer** [comment]
Vi måste bestämma oss för hur detta ska sparas och skapas innan det är lönt att implementera.

När jag pratade med @MatsDahlberg lät det som hela Pedigree-filen från början kommer submittas till databasen. Det skulle alltså bara vara tal om att uppdatera och lägga till värden i redan uppladdade pedigree-filer, eller?

Ska man kunna addera nya samples/personer till redan existerande pedigree-filer?

Hur gör vi när ett prov sekvenseras om en andra gång?

Borde vi inte också spara information som gäller hela familjen här också? Finns sådan data?

**Comment by MatsDahlberg** [comment]
Det måste göras om hur pedigree-datan sparas i databasen. Just nu så sparas all data som en stor text-massa. 

pedigree.txt måste istället parsas och sparas i dess enskilda komponenter.

**Comment by robinandeer** [comment]
Var det inte en sådan Pedigree-parser som @moonso höll med?

**Comment by MatsDahlberg** [comment]
Tycker vi väntar med detta tills vi har har detta på plats:
- Sökning och display av varianter
- IGV integration
- Comments på varianter och familjer

Så vi tar det om en vecka eller två.

**Comment by moonso** [comment]
Jag har precis skrivit en pedigree parser idag:) 
Vad är det ni tänker kring det, jag kanske kan lägga in funktioner som ni behöver?

**Comment by robinandeer** [comment]
@MatsDahlberg Visst, skrev det mest för att komma ihåg.

@moonso
- [ ] Den får gärna konvertera fram-och-tillbaka mellan `\t` (tab-separerad) och JSON/YAML-format.

**Comment by moonso** [comment]
Ok, du kan visa mig hur det ska se ut så fixar jag det.

**Comment by henrikstranneheim** [comment]
Jag försöker hålla så mycket som möjligt av kommunikationen mellan MIP och Scout i yamlformat. Så yaml är det format som jag föredrar. Varje analys runda genererar idag en yaml file (qc_pedigree.yaml) som är ett utdrag av den informationen som användes i analysen baserat på den tab-sep pedigree filen. Det finns således två pedigree filer en som skapas i Scout och en som skapas av MIP vid analysen baserat på klinikens. 

> Ska man kunna addera nya samples/personer till redan existerande pedigree-filer?

Ja. Alla data ska även kunna uppdateras. Jag tycker dock vi kan begränsa oss till de headers som finns i den nuvarande dokumentationen till att börja med. 

> Hur gör vi när ett prov sekvenseras om en andra gång?
> 
> Borde inte påverka så mycket. Alla entries i en pedigree läses in som separerade listor (för tab-sep) filen eller hash of arrays (yaml), och MIP väljer den mest aktuella informationen där det är relevant t.ex om två olika capturekit har använts (mest aktuella ska stå sist i varje entry). All data skrivs över vid den andra analysen och sampleIfnfo filen uppdateras automatiskt med den nya informationen. Min tanke är att Scout kan ska använda sparade md5sums för varje sampleInfo fil för att detektera att en ny analys har skett och importera nya pointers och tillhörande datafiler automatiskt. Visionen är att detta ska bli ett självuppdaterande system så långt det är möjligt.
> 
> Borde vi inte också spara information som gäller hela familjen här också? Finns sådan data?

Alla individer som tillhör kohorten (i CMMS fall familjen) bör ha sin metadata registrerad i pedigree filen. Det gör vi redan idag för de headers som är definerade. Vi (eller jag:) behöver dock föra in en koll på vilka prover som har sekvenserats och ska inkluderas i analysen. Det kan man bestämma från MIPs cmd men det vore snyggast om det gjordes automatiskt. 

Jag håller med Mats att fokus bör ligga på de tre punkter han tog upp tidigare med ett tillägg och det är generation av kliniska rapporter (pdf).

On 05 Feb 2014, at 14:32, Måns Magnusson notifications@github.com wrote:

> Ok, du kan visa mig hur det ska se ut så fixar jag det.
> 
> —
> Reply to this email directly or view it on GitHub.

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory, KISP
SE-171 65 Solna, Sweden

E-mail: henrik.stranneheim@scilifelab.se
Phone: +46 (0)8 524 81487 (Office) 
Phone: +46 (0)736251487 (Mobile)
Visiting address: Tometebodavägen 23A

**Comment by robinandeer** [comment]
@moonso @henrikstranneheim Konvertering mellan JSON/YAML/Dictionary (Hash) borde vara trivialt. Alltså borde alla alternativ stödjas i vilket fall. Ref: http://jsontoyaml.com/#python

> MIP väljer den mest aktuella informationen där det är relevant t.ex om två olika capturekit har använts

Frågan är bara hur detta uppdateras på bästa sätt. Jag antar att vi inte vill att klinikerna ens ska ha möjlighet att skriva över t.ex. det första capture kittet när de uppdaterar en Pedigree-fil, etc.

> Jag håller med @MatsDahlberg att fokus bör ligga på de tre punkter han tog upp tidigare med ett tillägg och det är generation av kliniska rapporter (pdf).

Det är väl mest på min spelplan som rapporten ligger. Det bör nog för tillfället bara automatiskt genereras för varje familj och sedan sparas någonstans för eventuell nedladdning. Bara att serva som en static file för @MatsDahlberg.

**Comment by henrikstranneheim** [comment]
> Frågan är bara hur detta uppdateras på bästa sätt. Jag antar att vi inte vill att klinikerna ens ska ha möjlighet att skriva över t.ex. det första capture kittet när de uppdaterar en Pedigree-fil, etc.
> 
> Låter bra. Vi får definiera vilka kolumner man ska ha rätt att skriva över helt och vilka man får göra tillägg. Det kan dock bli lite bökigt. Kanske enklast i början att tillåta skriva över allt och se hur det funkar. Alternativt att en admin (typ jag, du och Mats) har fullständiga rättigheter över pedigree filen. 

On 06 Feb 2014, at 07:31, Robin Andeer notifications@github.com wrote:

> @moonso @henrikstranneheim Konvertering mellan JSON/YAML/Dictionary (Hash) borde vara trivialt. Alltså borde alla alternativ stödjas i vilket fall.
> 
> MIP väljer den mest aktuella informationen där det är relevant t.ex om två olika capturekit har använts
> Frågan är bara hur detta uppdateras på bästa sätt. Jag antar att vi inte vill att klinikerna ens ska ha möjlighet att skriva över t.ex. det första capture kittet när de uppdaterar en Pedigree-fil, etc.
> 
> Jag håller med @MatsDahlberg att fokus bör ligga på de tre punkter han tog upp tidigare med ett tillägg och det är generation av kliniska rapporter (pdf).
> Det är väl mest på min spelplan som rapporten ligger. Det bör nog för tillfället bara automatiskt genereras för varje familj och sedan sparas någonstans för eventuell nedladdning. Bara att serva som en static file för @MatsDahlberg.
> 
> —
> Reply to this email directly or view it on GitHub.

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory, KISP
SE-171 65 Solna, Sweden

E-mail: henrik.stranneheim@scilifelab.se
Phone: +46 (0)8 524 81487 (Office) 
Phone: +46 (0)736251487 (Mobile)
Visiting address: Tometebodavägen 23A

**Comment by robinandeer** [comment]
Lite naivt skulle jag designa en JSON-pedigree-fil (from scratch) så här.
(YAML är teoretiskt likadant fast med annat syntax)
- Undvik specifika termer som "SciLife" och "CMMS" för att göra det generellt.
- Tydligare sex/phenotype beskrivningar än 1/0/2...
- Riktiga listor istället för kommaseparerade strängar
- `null` istället för "NA" (standard)

Synd bara att vi inte använder en NoSQL document database.

```
{
  "family_id": "99", 
  "samples": [
    {
      "sample_id": "99-1-1A", 
      "father": "99-2-1U", 
      "mother": "99-2-2U", 
      "sex": "male", 
      "phenotype": "affected", 
      "internal_id": "13-7866", 
      "tissue_origin": "blood", 
      "isolation_kit": "Qiagen midi", 
      "isolation_date": null, 
      "isolation_personnel": null, 
      "physician": "TS", 
      "inheritance_models": [
        "AR", 
        "AR_compound", 
        "AD_denovo", 
        "X", 
        "X_denovo"
      ], 
      "phenotype_terms": [], 
      "seq_id": "WES10", 
      "sequencing_provider_id": "A.Wedell_13_04", 
      "capture_kit": "Agilent_SureSelect.V5", 
      "capture_date": null, 
      "capture_personnel": null, 
      "clustering_date": null, 
      "sequencing_kit": null, 
      "clinical_db": "dbEP.v.1.0"
    }, 
    {
      "sample_id": "99-2-2U", 
      "father": null, 
      "mother": null, 
      "sex": "female", 
      "phenotype": "unaffected", 
      "internal_id": "13-7866", 
      "tissue_origin": "blood", 
      "isolation_kit": "Qiagen midi", 
      "isolation_date": null, 
      "isolation_personnel": null, 
      "physician": "TS", 
      "inheritance_models": [], 
      "phenotype_terms": [], 
      "seq_id": "WES10", 
      "sequencing_provider_id": "A.Wedell_13_04", 
      "capture_kit": "Agilent_SureSelect.V5", 
      "capture_date": null, 
      "capture_personnel": null, 
      "clustering_date": null, 
      "sequencing_kit": null, 
      "clinical_db": "dbEP.v.1.0"
    }, 
    {
      "sample_id": "99-2-1U", 
      "father": null, 
      "mother": null, 
      "sex": "male", 
      "phenotype": "unaffected", 
      "internal_id": "13-7866", 
      "tissue_origin": "blood", 
      "isolation_kit": "Qiagen midi", 
      "isolation_date": null, 
      "isolation_personnel": null, 
      "physician": "TS", 
      "inheritance_models": [], 
      "phenotype_terms": [], 
      "seq_id": "WES10", 
      "sequencing_provider_id": "A.Wedell_13_04", 
      "capture_kit": "Agilent_SureSelect.V5", 
      "capture_date": null, 
      "capture_personnel": null, 
      "clustering_date": null, 
      "sequencing_kit": null, 
      "clinical_db": "dbEP.v.1.0"
    }
  ]
}
```

**Comment by MatsDahlberg** [comment]
Det bästa är antagligen att Scout har en egen MongoDB där pegdigree och även 'family comments' och 'variant comments' sparas.

På så sätt separeras all data som användaren kan manipulera från den data som jag servar via clinicalDB.

Det är så det gamla interfacet funkar. Skulle kännas bättre att separera ut data som användaren kan manipulera i en separat databas och inte blanda den med den analysdata som jag parsar från rådata.

**Comment by robinandeer** [comment]
Spelar det någon roll att man startar en MongoDB server utöver MySQL?
Annars är https://mongolab.com/ är ett gratisalternativ om vi inte är tvungna att köra den "inom" nätverket.

**Comment by MatsDahlberg** [comment]
Visst skulle man kunna köra en server ute i ett moln, men jag tror det skulle vara bättre att ladda ner mongoDB från http://www.mongodb.org/ och ha en lokal server på samma maskin som mysql snurrar.

Det finns bra stöd för access från flask: http://flask-pymongo.readthedocs.org/en/latest/

**Comment by robinandeer** [comment]
@MatsDahlberg Visst, det besluter lägger jag mig inte i :) Det är bara jag som lockas av att inte  behöva oroa sig för backup och liknande.

@MatsDahlberg Kommer jag prata direkt med MongoDB databasen isf?

**Comment by MatsDahlberg** [comment]
Japp, isåfall pratar du direkt med mongo. Backup av mongo är nästan trivialt, man får ut hela databasen som ett json-dokument som man sedan ber Eric att ta backupp på varje natt.
