### ISSUE TITLE
Add feature IGV

### ISSUE THREAD

**Issue by henrikstranneheim** [robinandeer/scout#30]
1. Needs to detect the "most complete" BAM file for each sample from the FDN_qc_sampleInfo.yaml file.
2.  Should display the GATKVariantRecalibration vcf file if present also recorded in the FDN_qc_sampleInfo.yaml file.

**Comment by robinandeer** [comment]
@MatsDahlberg How do I submit request for a variant-range?

**Comment by MatsDahlberg** [comment]
At the moment you can't you can only ask for a specific variant through the call:
http://clinical-db.scilifelab.se:8082/variants/2001982/igv.xml

This will give you a range of +-100 bases of the specific variant. If you like we can add a new call that isn't based on a variant but on a genomic coordinate. Something like:
http://clinical-db.scilifelab.se:8082/igv.xml/chr1/12345/456787

where "12345" is start_bp and "456787" is stop_bp.

**Comment by robinandeer** [comment]
Need to check whether it works as expected to stream BAM and download VCF-files. Something in Flask happens and http 500 is returned (internal error).

Sometimes works, sometimes doesn't. Flask-Login issue?

**Comment by MatsDahlberg** [comment]
Stänger denna tills vi stöter på problem.
