### ISSUE TITLE
Ändring av gene_model

### ISSUE THREAD

**Issue by MatsDahlberg** [robinandeer/scout#44]
I den gamla datan avslutades alltid varje gene_model-element med ';'.

Så är det inte längre. Nu används ':' och det förkommer bara om en variant har mer än en gene_model.

Ex, förut:
"gene_model": "AR_compound;AR_denovo;AR;"
"gene_model": "AR_compound;"

Blir nu:
"gene_model": "AR_compound:AR_denovo:AR"
"gene_model": "AR_compound"

Just nu är det bara familj 99 som har data som följer det nya sättet.

**Comment by robinandeer** [comment]
Det går iaf åt rätt håll.
