### ISSUE TITLE
Nya kolumner i familj 99

### ISSUE THREAD

**Issue by MatsDahlberg** [robinandeer/scout#45]
Nu har jag adderat kolumnerna polyphen_var_human och GT_call_filter till databasen.
Det är bara familj 99 som har data i dessa.

Dessa två returneras tex av:
/families/99/filter
/variants/[\d+]

**Comment by robinandeer** [comment]
Är GT_call_filter "flyttat" från `variants/<variant_id>/gtcall`? Alltså inte med för varje samples GT Call (för familj 99)?

**Comment by MatsDahlberg** [comment]
Det stämmer. GT_call_filter har flyttat från gt_call för alla nya familjer.
